apiVersion: v1
kind: Service
metadata:
  name: customer-details
  namespace: imo
spec:
  selector:
    app: details
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30036
    protocol: TCP